#+TITLE: Shun's org notes

Welcome! I'm Shun, a novice software engineer. Here I publish my Org notes to share cool things I discover along the way.

I'm a daily driver of Nix & Emacs; consequently, most of my notes revolve around these two ecosystems.


* TIL: Sieve (mail filtering language)

I use Fastmail for my emails, and today I found that you can set a custom mail filtering rule using language called [[https://en.wikipedia.org/wiki/Sieve_(mail_filtering_language)][Sieve]].

Apparently there is also a [[https://datatracker.ietf.org/doc/html/rfc5804][protocol to manage Sieve script]], but Fastmail [[https://www.fastmail.help/hc/en-us/articles/360058753814-Sieve-frequently-asked-questions#using][doesn't support it]] :( I thought of writing a Just script or a Terraform provider, but too bad.

However: Fastmail supports [[https://www.fastmail.com/dev/][JMAP API]] (!) so if I really wanted to, I /can/ use =SieveScript/set=. But I'm too lazy. JMAP is crazytown.

Side note, Fastmail is awesome. Highly recommend.

* (macOS) Manage display resolution via CLI

There seem to be no official way to change display resolution from the cli on macOS, but [[https://github.com/p00ya/displaymode][p00ya/displaymode]] worked really well for me. I've fixed few stuffs & Nixified it, so feel free to try it out:

#+begin_src console
  nix run sourcehut:~ueda/monorepo#displaymode
#+end_src

I put this in Home Manager's activation:

#+begin_src Nix
  home = {
    activation = {
      # Darwin-specific activation script
      darwin = lib.mkIf pkgs.stdenv.hostPlatform.isDarwin (
        lib.hm.dag.entryAfter [ "writeBoundary" ] ''
          # Set display resolution, mine is 14-inch.
          ${lib.getExe pkgs.displaymode} t 1800 1169
        ''
      );
    };
  };
#+end_src

=p00ya/displaymode= is licensed under the Apache-2.0 license.

* Using S3 as a Nix cache

Cachix is too expensive so I use S3 (well, technically Cloudflare R2 because it's S3-compatible and egress-free) as a Nix cache, with a following script:

#+begin_src console
  #!/usr/bin/env bash

  set -euo pipefail

  signkey=$(mktemp)

  trap 'rm -f $signkey' EXIT

  echo "$NIX_CACHE_SIGNING_KEY" >"$signkey"

  nix store sign --key-file "$signkey" --all

  nix path-info --all |
    grep -v -E '\.(drv|check|drv\.chroot|lock)$' |
    xargs -n 50 -P 8 sudo -i nix copy --to "$NIX_CACHE_SUBSTITUTER"
#+end_src

Intended for use in CI. Signs everything is the store, filters things we're interested in, and =nix copy= (in chunks to avoid command being too long) to the backend. Pretty straight forward but works well for me.

Side note: if you're using S3 as a Nix store, check this out: [[https://github.com/anteriorcore/terraform-aws-s3-nix-lru-cache][anteriorcore/terraform-aws-s3-nix-lru-cache]]. It uses S3 access logs to GC. Pretty neat.

* Does anyone find Google's AI search usful?

I've never found Google's "AI Overview" particularly helpful. It's been more distracting than useful, and worse still, there seems to be no way to turn it off.

Since then, I've switched to DuckDuckGo's “No AI” search at https://noai.duckduckgo.com/, and that has worked well for me.

Here's how to configure it in Home Manager. I use Librewolf, but this should work the same way in Firefox:

#+begin_src nix
  librewolf = {
    enable = true;
    policies = {
      GenerativeAI.Enabled = false; # Bonus: turn off other Firefox AI features
    };
    profiles.<my-profile> = {
      search = {
        force = true;
        default = "ddg-noai";
        engines = {
          "ddg-noai" = {
            urls = [
              {
                template = "https://noai.duckduckgo.com/";
                params = [ (lib.nameValuePair "q" "{searchTerms}") ];
              }
            ];
            definedAliases = [ "@noai" ];
          };
        };
      };
      ...
    };
  ...
  };
#+end_src


* histsync: sync shell history with pass

[[https://github.com/atuinsh/atuin][Atuin]] is super cool: it let's you sync shell history across machine, but few issues for me:

1. Requires a server. I distrust managed public servers and don't want to host my own.
2. Heavy LLM usage for development. I have nothing against LLMs but I try to avoid them.

I use [[https://www.passwordstore.org/][password-store]] (pass), so why don't I leverage this:

#+begin_src nix
  bash = {
    enable = true;
    # ... 
    initExtra = ''
      histsync() {
        # Append currently history to HISTFILE
        history -a

        # Entry name in pass - I separate history by host
        local passentry="ShellHistories/$HOSTNAME"

        # Merge HISTFILE and pass entries, remove duplicates, update HISTFILE
        (cat "$HISTFILE" 2>/dev/null; pass show "$passentry" 2>/dev/null) |
          awk '!a[$0]++' |
          ${pkgs.moreutils}/bin/sponge "$HISTFILE"

        # Update pass entry with the merged history
        <"$HISTFILE" pass insert -mf "$passentry"

        # Reload history for current session
        history -c
        history -r
      }

      # ...
    '';
  };
#+end_src

Note: the merge logic will not work if you use timestamps.

* password-store: nerd snipe quagmire

I've been using Apple's Passwords.app, but [[https://www.passwordstore.org/][password-store]] (pass) seemed very cool, and since I already did the heavy-lifting of setting up the YubiKey, I decided to migrate.

Another reason that convinced me: [[https://www.gnu.org/software/emacs/manual/html_mono/auth.html#The-Unix-password-store][Emacs supports pass as an auth-source natively]]! Here is a sample:

#+BEGIN_SRC emacs-lisp
  (auth-source-pass-enable)

  (auth-source-pass-get 'secret "foo/bar")
#+END_SRC

You can also use [[https://git.zx2c4.com/password-store/tree/contrib/emacs/password-store.el][password-store.el]] to interact with pass via Emacs.

* Setting up my YubiKey

To manage my GPG key, I set up my YubiKey (5C NFC). This guide was extremely helpful: https://github.com/drduh/YubiKey-Guide.

One note: if you're using ed25519 for your signing key, make sure to set =KEY_TYPE=cv25519= before creating the encryption (E) subkey - GPG will complain otherwise.
